[tool.poetry]
name = "starksheet"
version = "0.1.0"
description = ""
authors = ["Clément Walter <clement0walter@gmail.com>"]
packages = [
    { include = "*.py" },
]

[tool.poetry.dependencies]
python = "~3.9"
cairo-lang = "^0.9.1"
starknet-devnet = "^0.2.4"
pytest = "^7.1.2"
pytest-asyncio = "^0.18.3"
openzeppelin-cairo-contracts = "^0.2.0"
pandas = "^1.4.3"
case-converter = "^1.1.0"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
isort = "^5.10.1"
ipython = "^8.4.0"
tweepy = "^4.10.0"

[tool.pytest.ini_options]
pythonpath = [
  "."
]
asyncio_mode="auto"
filterwarnings = [
  'ignore:Using or importing the ABCs:DeprecationWarning',  # from frozendict
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
